type Order {
  id: String!
  exchange: String!
  amount: Float!
  price: Float!
}

type Query {
  orders: [Order]
}

type Mutation {
  placeOrder(amount: Float!, price: Float!, exchange: String!): Order!
  removeOrder(orderId: String!): String!
}
